# Generated by Django 4.2.4 on 2023-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('news_text', models.TextField()),
                ('news_in_picname', models.TextField(blank=True, null=True)),
                ('news_in_picurl', models.TextField(blank=True, null=True)),
                ('picname', models.TextField(blank=True, null=True)),
                ('picurl', models.TextField(blank=True, null=True)),
                ('news_date', models.FloatField()),
            ],
        ),
    ]
