# Generated by Django 4.2.4 on 2023-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_brief',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
