# Generated by Django 4.2.4 on 2023-10-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subcategory_news_news_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name_sub',
        ),
    ]
