# Generated by Django 4.2.4 on 2023-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
