# Generated by Django 4.2.4 on 2023-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
