# Generated by Django 4.2.4 on 2023-09-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=100)),
                ('name_page', models.CharField(max_length=100)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('copyright', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('icon_name_header', models.TextField(blank=True, null=True)),
                ('icon_url_header', models.TextField(blank=True, null=True)),
                ('icon_name_footer', models.TextField(blank=True, null=True)),
                ('icon_url_footer', models.TextField(blank=True, null=True)),
                ('favicon_name', models.TextField(blank=True, null=True)),
                ('favicon_url', models.TextField(blank=True, null=True)),
                ('seo_text', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
